paths:
  app: '../app'
  jquery: '../jquery'
shim:
  backbone:
    deps: ['underscore', 'jquery','handlebars','require']
    exports: 'Backbone'
  underscore:
    exports: '_'
  jquery.smartbanner: ['jquery']